credentials:
  usernames:
    actumucet:
      email: actumucet@gmail.com
      name: Actum Ucet
      password: '$2b$12$PvzATBUnMj40j7HYgIIhf.n4jmPyf2LAOfUjAUQPb7XCXRMf.uCzy' # Placeholder for hashed password of 'abc'  
cookie:
  expiry_days: 30
  key: 'dataapp' # Must be string
  name: some_cookie_name
preauthorized:
  emails: