credentials:
  usernames:
    actumucet:
      email: actumucet@gmail.com
      name: Actum Ucet
      password: '$2b$12$PvzATBUnMj40j7HYgIIhf.n4jmPyf2LAOfUjAUQPb7XCXRMf.uCzy' # Placeholder for hashed password of 'abc'
     
        # Placeholder for hashed password of 'def'
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails: