[snowflake] 
user = "KEBOOLA_WORKSPACE_608156898"
password = "35zWKbK2rsWeY7q63zZhy6EEHh4PAawM" 
account = "keboola.eu-central-1.snowflakecomputing.com"
warehouse = "KEBOOLA_PROD_SMALL"
database = "KEBOOLA_3730"
schema = "WORKSPACE_611037349"
