[snowflake] 
user = "KEBOOLA_WORKSPACE_611037349"
password = "35zWKbK2rsWeY7q63zZhy6EEHh4PAawM" 
account = "keboola.eu-central-1.snowflakecomputing.com"
warehouse = "KEBOOLA_PROD_SMALL"
database = "KEBOOLA_3730"
schema = "WORKSPACE_611037349"

github_username = "DmitriiSid"
github_password = "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"